### ISSUE TITLE
How to fix UnsignedLongType?

### ISSUE THREAD

**Issue by awalter17** [imglib/imglib2#102]
Hello all!

I noticed several issues with [UnsignedLongType](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/type/numeric/integer/UnsignedLongType.java). 
1. getMaxValue( ) is 0xffffffffL and it should be 0xffffffffffffffffL (this value cannot be represented in java as an unsigned value)
   - Maybe we could do something similar to what is done in [Unsigned128BitType](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/type/numeric/integer/Unsigned128BitType.java)?
2. compare( ) doesn't work for negative values
   - Can't compare unsigned `long`s larger than 2<sup>63</sup> - 1
   - Since there is no larger primitive than long, it uses long
     - this is also inconsistent with how the other unsigned types implement compare
3. get( ) returns a long
   - Calling get( ) on an UnsignedLongType can then return a negative value, if it was constructed with a negative 
   - Maybe it should return a `BigInteger` as to return unsigned `long`s larger than 2<sup>63</sup> - 1
   - Inconsistent with other unsigned types which return the next larger primitive (which can't be done here)

I think one possible way to fix some of these issues would be to utilize `BigInteger` similar as to what is done in [Unsigned128BitType](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/type/numeric/integer/Unsigned128BitType.java). However, I am not certain if this is the best way to solve these issues. 

Please let me know your thoughts on this, or if anything I said was unclear.

**Comment by tpietzsch** [comment]
good catch @awalter17!

Regarding `compare()`, something like this should work:
```
	static int compare( final long a, final long b )
	{
		return a < 0 ?
				( b < 0 ? ( int ) ( a - b ) : 1 ) :
				( b < 0 ? -1 : ( int ) ( a - b ) );
	}
```
The logic is sound, I tried it with bytes:
```
	static int compare( final byte a, final byte b )
	{
		return a < 0 ?
				( b < 0 ? a - b : 1 ) :
				( b < 0 ? -1 : a - b );
	}

	public static void main( final String[] args )
	{
		for ( int a = 0; a <= 255; ++a )
		{
			for ( int b = 0; b <= 255; ++b )
			{
				final int i = compare( ( byte ) a, ( byte ) b );
				if ( i == 0 )
				{
					if ( a != b )
						System.out.println( "error: " + a + " == " + b );
				}
				else if ( i < 0 )
				{
					if ( a >= b )
						System.out.println( "error: " + a + " < " + b );
				}
				else
				{
					if ( a <= b )
						System.out.println( "error: " + a + " > " + b );
				}
			}
		}
	}
```
However, I didn't verify it for the long. Could you test it?


Regarding `getMaxValue()`, I would use the same approach as Unsigned128BitType, as you suggested.


For `get()` I'm uncertain. I think it is useful to have `get()` (and `set()`) with values coded as (signed) `long`. We could simply add a `getAsBigInteger()`. @axtimwalde, @StephanPreibisch what do you think?

**Comment by bogovicj** [comment]
Closing, since it looks like #109 fixed this.
