### ISSUE TITLE
PeriodicalInterpolatorFactory

### ISSUE THREAD

**Issue by LeonYang5114** [imglib/imglib2#103]
Do we want to have a PeriodicalInterpolatorFactory so that scaling images can be more consistent using different interpolation methods?

**Comment by axtimwalde** [comment]
@LeonYang5114 I don't get it, could you elaborate?

**Comment by LeonYang5114** [comment]
@axtimwalde I am working on refactoring an <a href="https://github.com/imagej/imagej-deprecated/blob/master/src/main/java/net/imglib2/ops/operation/iterableinterval/unary/Resample.java#L81">ImageJ class</a> which uses some InterpolatorFactory implementations. I recognize that for periodical resampling, the corresponding InterpolatorFactory does not exist. I think it might be good to have such implementation, which could make resampling codes that use InterpolatorFactory more extensible.

**Comment by axtimwalde** [comment]
I still don't get it.  In that class, PERIODICAL does not refer to interpolation but to how the input is extended (and means periodic)---does that make sense at all?

**Comment by LeonYang5114** [comment]
@axtimwalde I was thinking that adding periodical as a special case for the interpolation might be handy for resampling, but probably that's not proper. You are right about that. Thanks for the explanation.
