### ISSUE TITLE
Confusing FinalDimensions constructor with a single int parameter

### ISSUE THREAD

**Issue by rimadoma** [imglib/imglib2#121]
I was writing test code, and ran into this confusing constructor when calling

```
final int intervalSize = 10;
new FinalDimensions(intervalSize);
```

and it took me a while to figure out why later on I got an `ArrayIndexOutOfBoundsException`. What this single parameter constructor actually does is 

```
public FinalDimensions( final int n )
{
    this.dimensions = new long[ n ];
}
```

I couldn't find any usages for this constructor, and I think it should eventually be removed, or at least marked `@deprecated`.

**Comment by ctrueden** [comment]
I agree with @rimadoma: seems weird to ever need an N-dimensional image but with 0 length for each dimension!

**Comment by tpietzsch** [comment]
I agree, too. Let's deprecate it

**Comment by tpietzsch** [comment]
Because this never actually happened, I'll just removed it for upcoming imglib2 4.0.0 release
