### ISSUE TITLE
consider adding method for union of two intervals

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2#124]
Intervals has a method to compute an intersection
(https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/util/Intervals.java#L206-L231)

but there is no method to compute the union. 
I'd be happy to make a pull request with this if it's of interest.

**Comment by tpietzsch** [comment]
@bogovicj Yes, this is of interest and a PR would be cool!

**Comment by bogovicj** [comment]
Great, will do :-)

**Comment by bogovicj** [comment]
Great, thanks @tpietzsch
Fixed by pull request #125 and closes this issue.
