### ISSUE TITLE
Should Type implement a valueEquals method?

### ISSUE THREAD

**Issue by axtimwalde** [imglib/imglib2#130]
I keep finding myself in places where I want to test whether two samples have the same value.  In the conventional Java world, the `Object.equals(Object)` method would be the right thing to use, unfortunately, this is not well suited for ImgLib2 because (a) we are explicitly not interested in equivalency on the reference level, (b) `Object.equals(Object)` is not typed and would thus require dynamic casting, (c) the JDK uses `Object.equals(Object)` in other contexts (e.g. `HashSet`) that would trigger potentially unintended side-effects.  Overriding `Object.equals(Object)` requires that we think about how to override `Object.hashCode()` which is not currently my intention.

I would introduce a single method interface `type.operators.ValueEquals` and see how far I can got from there.  If you have comments or red flags that I cannot see right now, please let me know.

**Comment by tpietzsch** [comment]
@axtimwalde As we would say in german: "Das Kind ist schon in den Brunnen gefallen"
https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/type/numeric/real/AbstractRealType.java#L132-L148
I don't remember who introduced it originally and why. I just remembered @ctrueden PR to make it more consistent. If @axtimwalde would rather remove it, maybe you two can discuss options...

**Comment by axtimwalde** [comment]
@tpietzsch, oh well...  It doesn't hurt to have that in parallel.  We do, however, lack a method to generically match the values of e.g. `ARGBType` and `RealType`.  I will give it a shot.

**Comment by tpietzsch** [comment]
@axtimwalde sounds good. BTW the "axtimwalde was assigned by tpietzsch just now" was some keyboard shortcut I pressed mistake and I don't know how to revert it...

**Comment by ctrueden** [comment]
@tpietzsch If you push the `?` key it will tell you.

**Comment by axtimwalde** [comment]
@tpiezsch thanks for the trust assignment, makes me feel trusted ;).

**Comment by axtimwalde** [comment]
I opened a pull request https://github.com/imglib/imglib2/pull/132
