### ISSUE TITLE
Problem with Views

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2#133]
Following code isn't doing what it is expected to do:

```
ArrayImg<FloatType, FloatArray> floats = ArrayImgs.floats(10, 10, 5);
		IntervalView<FloatType> sliceWithAddDim = Views.addDimension(Views.hyperSlice(floats, 2, 3), 0, 0);

		Cursor<RealComposite<FloatType>> cursor = Views.iterable(Views.collapseReal(sliceWithAddDim)).cursor();

		long[] tmp = new long[cursor.numDimensions()];
		while (cursor.hasNext()) {
			cursor.next().get(0);
			cursor.localize(tmp);
			System.out.println(Arrays.toString(tmp));
		}
```
Looks like something is going wrong in the `SlicingRandomAccess` in combination with `Composite` or do I do something wrong here?

**Comment by tpietzsch** [comment]
what is it supposed to do?

**Comment by dietzc** [comment]
on master I can't reproduce either. I will anyway what caused the problem. thanks!

**Comment by dietzc** [comment]
it was a problem in imglib2 2.7 which seems to be fixed. sorry for not double-checking with the master before.
