### ISSUE TITLE
HyperSlicesView

### ISSUE THREAD

**Issue by axtimwalde** [imglib/imglib2#134]
I added the naive `HyperSlicesView` implementation from the hackathon at Janelia last week

https://github.com/imglib/imglib2/tree/hyperslicesview

This creates a new `HyperSlice` per each `get()` on the `RandomAccess` which is probably just fine if the size of the `HyperSlices` is significant and inner loops dominate the operation.  It is also the only safe method that I could come up with that enables to nest `HyperSlicesViews` and use independent `RandomAccesses` on them.  Yet missing is an `Interval` version for convenience (can be done by interval-ing the results now).  Do we want this?

**Comment by hanslovsky** [comment]
The PR was merged, so this should be closed, right?

**Comment by tpietzsch** [comment]
👍
