### ISSUE TITLE
Allow creating BoolType images, e.g. using factories

### ISSUE THREAD

**Issue by haesleinhuepf** [imglib/imglib2#140]
At the moment it is not possible to create an Img<BoolType> using ArrayImgs.bool(...) only BitTypes are possible. But if you cannot create Img<BoolType>, it is hard to make an actual copy of a binary image, e.g. resulting from a RasterizedPolygon in imglib-roi.

By the way: I guess the root of the issue is that BoolType is no NativeType, but it's hard to guess why... 

And finally: Is there a real need for having BoolType and BitType? Wouldn't one be enough?

**Comment by dietzc** [comment]
Why can't you create  a `BitType` img and copy the images into this  img? If you have restrictions on e.g. `RAI<BoolType>` you could generalize this code to `RAI<B extends BooleanType<B>`. 

The difference between `BoolType` and `BitType` is that `BitType` is for memory reasons backed by a `long[]`, in contrast to saving all the `boolean`s themselves. If you (like with `Regions`) want to calculate values on the fly or create the types manually you use `BoolType`. Both inherit from `BooleanType`.

**Comment by haesleinhuepf** [comment]
There is another difference between BitType and BoolType: You cannot create BoolType images, e.g. using factories ;-) I really would like to know why.

But the hint of changing all my stuff from `BoolType` to `B extends BooleanType<B>` is really good! Thanks!

**Comment by tpietzsch** [comment]
@haesleinhuepf 
> There is another difference between BitType and BoolType: You cannot create BoolType images, e.g. using factories ;-) I really would like to know why.

`BitType` is a `NativeType`, but `BoolType` isn't. You could create a `BoolType` `ListImg`, but not an `ArrayImg` because that requires `NativeType`.

The general idea is to use `BitType` for stuff, like binary mask images, where you actually store data. `BoolType` is used for on-the-fly generated stuff like a "binary mask view" of a region in a labeling. In the latter case all you want is a single Type object wrapping a `boolean` and doing this by bit flipping etc in `BitType`s `long[]` underlying array is wasted effort.

As @dietzc pointed out, algorithms should be typed on `B extends BooleanType<B>` to be able to deal with both variants.

**Comment by ctrueden** [comment]
My 2 cents: we could make `BoolType` extend `NativeImg` by making a `BooleanArray` backed by `boolean[]`. By why? It would be highly inefficient compared to `BoolType`, with nearly no advantages. The only advantage I can think of is for integration with other software that uses `boolean[]` as its native data structure somehow; then it might be convenient. But so far, AFAIK, no one has needed this.

**Comment by haesleinhuepf** [comment]
Now, that I know that [my] custom implementations should take `B extends BooleanType` as input, I'm fine with not changing `BoolType`. However, this is absolutely not obvious. Or did I miss an "ImgLib development guide" explaining it like @tpietzsch just did:

"The general idea is to use `BitType` for stuff, like binary mask images, where you actually store data. `BoolType` is used for on-the-fly generated stuff like a "binary mask view" of a region in a labeling."

?

**Comment by ctrueden** [comment]
@haesleinhuepf Would you care to flesh out the javadoc for these respective classes, pasting the words from various folks above? It would be very helpful.

**Comment by haesleinhuepf** [comment]
Of course, I'll do that. However, at some point it would be very helpful to have such a development guide... Cross issue: this guide document would also be the right place to say things like "Never require `Img`."

**Comment by ctrueden** [comment]
@haesleinhuepf One problem is that there are so many "things": ImgLib2, Ops, ImageJ2, Fiji... so people look in different places for such guides. Where would you expect to find information such as "never require Img"? That is largely an Ops rule, although it holds for general ImgLib2 dev too.

**Comment by ctrueden** [comment]
Should we create an uber-dev-guide?

**Comment by haesleinhuepf** [comment]
We started refactoring our stuff at some point from requireing `Imgs` to requireing `RandomAccessibleIntervals`; I just refactored some stuff to require `B extends BooleanType` instead of `BoolType`. So I guess, these are best-practice-rules . We could start this as section or sub-page of http://imagej.net/Writing_plugins . And with "we" I mean: I can support _others_ by raising questiions. But _others_ are much more experienced than I am. And thus, these _others_ should be the actual authors of a "best practices" page on the wiki ;-)

**Comment by ctrueden** [comment]
> And thus, these others should be the actual authors of a "best practices" page on the wiki ;-)

These _others_ are pretty busy with other things. And that is always the case, sadly. If you write it, it will get written. And "others" will review and edit the content.
