### ISSUE TITLE
RandomAccessiblePair looses out of bounds for elements

### ISSUE THREAD

**Issue by stelfrich** [imglib/imglib2#144]
I have worked with @dietzc on refactoring some parts of Ops with respect to local neighborhoods. In that context, we came across an issue with a `RandomAccessiblePair<Neighborhood<I>, I>` and `Views.extend()`.

I have created a MWE in [RandomAccessiblePairWithNeighborhoodTest](https://github.com/stelfrich/imglib2-algorithm/blob/5acc2c489b6566bd7db7e48edafb38ded5c084f5/src/test/java/net/imglib2/algorithm/neighborhood/RandomAccessiblePairWithNeighborhoodTest.java). In this case, it seems that the `Views.extend()` in L26 might be lost during `Views` optimization, which results in `ArrayIndexOutOfBoundsException`s when accessing the source through a `Neighborhood` of the `RandomAccessiblePair`.

Is this a bug or a feature? (for our case it's definitely a bug..)

PS: The `RandomAccessiblePair` is awesome. Thanks @axtimwalde!

**Comment by tpietzsch** [comment]
this should be fixed by https://github.com/imglib/imglib2-algorithm/pull/30

**Comment by stelfrich** [comment]
Test passing. Thanks @tpietzsch!
