### ISSUE TITLE
SubsampleIntervalView ignores min/max of input RAI

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2#145]
The code below creates a 1d RAI over the interval [ -4, -1 ],
subsamples it by 2, then iterates over the result, printing the position of the cursor.

```java
// Interval [-4 -1]
FinalInterval interval = new FinalInterval( new long[]{-4 }, new long[]{ -1 });

// Some RAI over that interval
RandomAccessibleInterval<FloatType> rai = ConstantUtils.constantRandomAccessibleInterval( 
     new FloatType( 1f ), 1, interval );

// print the starting interval
System.out.println( Util.printInterval( rai )); 

// subsample by 2
SubsampleIntervalView<FloatType> subRai = Views.subsample( rai, 2 );

// print the subsampled interval
System.out.println( Util.printInterval( subRai ));

```

I expected the output to be:
```
[-4] -> [-1], dimensions (4)
[-4] -> [-3], dimensions (2) 
```
or something similar, but instead got:
```
[-4] -> [-1], dimensions (4)
[0] -> [1], dimensions (2)
```
Should we change the behavior to match my expectation?

This relates to calibration as well, and sure, I could put an interval on top of the output, but it seemed to me reasonable that SubsampleIntervalView would do it.

**Comment by hanslovsky** [comment]
I think `(0,1)` is ok for `min` and `max` of the new `RAI`. I can see why it is desirable to conservethe coordinate space of the original image but when we look at the pixels that are sampled (indicated by `x`)
```
-4 -3 -2 -1
 x     x   
```
the `max` should be `-2`. As a `RAI` does not have a stride in general and callers can always use the less specific type (`RAI` instead of `SubsampleIntervalView`) that would be inconsistent with `RAI.dimension( int )`.

**Comment by bogovicj** [comment]
@hanslovsky good point about missing stride, but here's a counterpoint:

The behavior here is not consistent with the behavior for an infinite RandomAccessible, where a subsampleInterval by 2 would map `[-4, -1]` to `[-2, -1]`.

Part of why this surprised me is that I expect the output of a subsampling to scale space *only*, but it also adds a shift.  Pinning the min is what I expected, and I could see a case for pinning the origin, but I *can't* see a convincing case for also shifting.

What would you think about the output interval being `[-2 -1]`?

In person, @axtimwalde said that this method should just not exist - that it should work on RandomAccessible's and not RandomAccessibleIntervals (Just want to loop in that thought).

**Comment by hanslovsky** [comment]
You are right about the added shift. I think your proposed solution (`[-2 -1]`) makes a lot of sense and would be the way to go here.

**Comment by bogovicj** [comment]
Going to ask @shrucis1 to look into this.

**Comment by bogovicj** [comment]
@axtimwalde pointed me to this sentence in [the javadoc](https://github.com/imglib/imglib2/blob/3016066a5c77969d1d5008a627475d6e98c251b4/src/main/java/net/imglib2/view/SubsampleIntervalView.java#L45-L46), indicating that the above is the desired behavior.  Am closing this issue.
