### ISSUE TITLE
AbstractConvertedRandomAccessibleInterval missing

### ISSUE THREAD

**Issue by hanslovsky** [imglib/imglib2#146]
There are 
 * `AbstractConvertedIterableInterval`
 * `AbstractConvertedIterableRandomAccessibleInterval`
 *  `AbstractConvertedRandomAccessible`
 *  `AbstractConvertedRealRandomAccessible`
in the `net.imglib2.converter` package but no `AbstractConvertedRandomAccessibleInterval`. Was there a decision against it or is because there was no need for it so far? If it is the latter, I will implement it and create a pull request.

**Comment by tpietzsch** [comment]
Probably it was the latter. Working around it with `Views.interval()` should not result in any performance hit, but if you want to add it directly, feel free!

**Comment by hanslovsky** [comment]
Resolved in #147
