### ISSUE TITLE
CompositeXYProjector does not handle View offsets correctly

### ISSUE THREAD

**Issue by Meyenhofer** [imglib/imglib2#161]
As reported in the Imagej forum:
http://forum.imagej.net/t/discrepancy-between-different-ways-of-displaying-views/5068
... the offsets from a View on an image is not rendered correctly when using scijava Display. However I suspect the bug to be in the CompositeXYProjector.map() method
https://github.com/imglib/imglib2/blob/6ec3a6fdb0d0b43290ddcddfbb83d644cbedeefe/src/main/java/net/imglib2/display/projector/composite/CompositeXYProjector.java#L160
It look as the min and max values should be determined by the source-image, not the target image.

**Comment by tpietzsch** [comment]
As discussed on the forum, the current behaviour is correct.
