### ISSUE TITLE
NLinearInterpolatorFactory : problem with linear interpolation; blue turns green

### ISSUE THREAD

**Issue by NicoKiaru** [imglib/imglib2#166]
This notebook shows the problem:
https://github.com/NicoKiaru/myIJNotebooks/blob/master/TestAsciiGeek.ipynb

Some pixels of the sky weirdly turn green when downscaling the image.

**Comment by axtimwalde** [comment]
The default `NLinearInterpolator` does not clamp.  Can you please try with
https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/interpolation/randomaccess/NLinearInterpolatorARGBFactory.java
?

**Comment by axtimwalde** [comment]
Related @tpietzsch: Shouldn't we move those over into ImgLib2 core?

https://github.com/bigdataviewer/bigdataviewer-core/tree/master/src/main/java/net/imglib2/interpolation/randomaccess

**Comment by NicoKiaru** [comment]
Hi and thanks for the suggestions @axtimwalde,

FYI, I'm at the learnathon in Dresden with @tpietzsch and @ctrueden , thus I showed them this error. They gave me some insights:
1 - The  NLinearInterpolatorARGBFactory gives this error : java.lang.ClassCastException: net.imglib2.type.numeric.integer.UnsignedByteType cannot be cast to net.imglib2.type.numeric.ARGBType
2 - But the net.imglib2.interpolation.randomaccess.ClampingNLinearInterpolatorFactory works !

**Comment by axtimwalde** [comment]
Excellent!  Another option that should work without clamping is to convert the sources to float
`Converters.convert(sourceRA, targetRA, TargetType)`

**Comment by tpietzsch** [comment]
> Related @tpietzsch: Shouldn't we move those over into ImgLib2 core?
> 
> https://github.com/bigdataviewer/bigdataviewer-core/tree/master/src/main/java/net/imglib2/interpolation/randomaccess

I already made an issue https://github.com/bigdataviewer/bigdataviewer-core/issues/28 ...
