### ISSUE TITLE
Document assumptions about when coordinates are defined

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2#167]
E.g.:

* For `IterableInterval`, are all coordinates within the `Interval` always iterated?
* For `RandomAccessibleInterval`, are all coordinates within the `Interval` always defined?
* How about for `RandomAccessible`? (Of course not.)
* How about `RealRandomAccessibleRealInterval`? `RealRandomAccessible`?

It would be helpful to answer this question clearly in the javadoc of each interface.

/cc @stelfrich

**Comment by ctrueden** [comment]
Note that there is a comment in `RealInterval` along these lines, as follows:

```java
 * An {@link RealInterval} over the real source domain. <em>Note</em> that this
 * does <em>not</em> imply that for <em>all</em> coordinates in the
 * {@link RealInterval} function values exist or can be generated. It only
 * defines where the minimum and maximum source coordinates are. E.g. an
 * {@link IterableRealInterval} has a limited number of values and a source
 * coordinate for each. By that, minimum and maximum are defined but the
 * {@link RealInterval} does not define a value for all coordinates in between.
```

This is the sort of statement which I think would be valuable to put explicitly in the context of each individual interface.

**Comment by awalter17** [comment]
The [ImgLib2-Accessibles](http://imagej.net/ImgLib2_-_Accessibles) page on the wiki answers:
> For `RandomAccessibleInterval`, are all coordinates within the `Interval` always defined?

(under the RandomAccessibles heading)

But it would be good to also have this information in the javadoc.

**Comment by ctrueden** [comment]
Thanks @awalter17. That was enough of a hint for me to go ahead and make a PR updating the javadocs.
