### ISSUE TITLE
Potential Inconsistency with Cursor Behaviors

### ISSUE THREAD

**Issue by awalter17** [imglib/imglib2#170]
Hello!

I noticed some inconsistencies between how a few of the `Cursor`s behave when they’re at an invalid position/index (either because `fwd()` has been called too many times or `jumpFwd()` went too far). Specifically, I was looking at `ArrayCursor`, `CellCursor`, `ListCursor`, and `PlanarCursor`.

For example, the below code snippet would have a different behavior for each of the four cursor types. Note: `img` is a `CellImg`, `ArrayImg`, etc. of `DoubleType`.

```
final Cursor< DoubleType > c = img.cursor();
while( c.hasNext() )
	c.fwd();
c.fwd(); // CellCursor throws IndexOutOfBoundsException
c.get(); // ListCursor throws ArrayIndexOutOfBoundsException
c.get().get(); // ArrayCursor throws IndexOutOfBoundsException
// PlanarCursor does not throw an error, when the cursor goes beyond the last plane
// it just keeps iterating the last plane
```

I noticed this issue because I was trying to use ops to convert a `CellImg< DoubleType, ? >` to `CellImg< BitType, ? >` .

```
final Img< DoubleType > img = new CellImgFactory< DoubleType >().create( 
	new long[] { 10, 20 }, new DoubleType() );
ops().convert().bit( img );
```

The above will throw an `IndexOutOfBoundsException`. The issue comes from the parallel unary [map](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/map/Maps.java#L287) method being used. This method computes the value and then progresses the `Cursor`. So cursors are progressed one step too far. This is fine for `ArrayImg` but not `CellImg`. 

This would not be an issue if all `Cursor`s could be placed at invalid indices/locations and then only gave an error if you tried to retrieve a value from said cursor. 

In my mind it would make sense that, all `Cursor`s could "exist" at invalid locations/indices without an issue and would only throw an error if you try to retrieve a value at an invalid index. However, I am not certain if this is the correct behavior? Nor am I certain each cursor should have to conform to this.

Please let me know your thoughts on this.

Thanks,

Alison

**Comment by axtimwalde** [comment]
The behavior for cursors moved beyond hasNext is not defined. Please change the unary map method accordingly. Progress first, then calculate.

On June 23, 2017 12:29:47 AM EDT, awalter17 <notifications@github.com> wrote:
>Hello!
>
>I noticed some inconsistencies between how a few of the `Cursor`s
>behave when they’re at an invalid position/index (either because
>`fwd()` has been called too many times or `jumpFwd()` went too far).
>Specifically, I was looking at `ArrayCursor`, `CellCursor`,
>`ListCursor`, and `PlanarCursor`.
>
>For example, the below code snippet would have a different behavior for
>each of the four cursor types. Note: `img` is a `CellImg`, `ArrayImg`,
>etc. of `DoubleType`.
>
>```
>final Cursor< DoubleType > c = img.cursor();
>while( c.hasNext() )
>	c.fwd();
>c.fwd(); // CellCursor throws IndexOutOfBoundsException
>c.get(); // ListCursor throws ArrayIndexOutOfBoundsException
>c.get().get(); // ArrayCursor throws IndexOutOfBoundsException
>// PlanarCursor does not throw an error, when the cursor goes beyond
>the last plane
>// it just keeps iterating the last plane
>```
>
>I noticed this issue because I was trying to use ops to convert a
>`CellImg< DoubleType, ? >` to `CellImg< BitType, ? >` .
>
>```
>final Img< DoubleType > img = new CellImgFactory< DoubleType
>>().create( 
>	new long[] { 10, 20 }, new DoubleType() );
>ops().convert().bit( img );
>```
>
>The above will throw an `IndexOutOfBoundsException`. The issue comes
>from the parallel unary
>[map](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/map/Maps.java#L287)
>method being used. This method computes the value and then progresses
>the `Cursor`. So cursors are progressed one step too far. This is fine
>for `ArrayImg` but not `CellImg`. 
>
>This would not be an issue if all `Cursor`s could be placed at invalid
>indices/locations and then only gave an error if you tried to retrieve
>a value from said cursor. 
>
>In my mind it would make sense that, all `Cursor`s could "exist" at
>invalid locations/indices without an issue and would only throw an
>error if you try to retrieve a value at an invalid index. However, I am
>not certain if this is the correct behavior? Nor am I certain each
>cursor should have to conform to this.
>
>Please let me know your thoughts on this.
>
>Thanks,
>
>Alison 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/imglib/imglib2/issues/170

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ctrueden** [comment]
To elaborate on @axtimwalde's comment a little: ImgLib2 favors performance over bounds checking. In other words, it is the responsibility of the caller to fulfill the preconditions. This is of course always true, but in ImgLib2 there are places—and `Cursor` is a prime example—where any sort of bounds checking will kill performance. In other words: the per-sample methods need to be as optimized as possible.

For debugging we could perhaps add a `DebugCursor` which performs explicit bounds checking all the time. But it should never be used in production code—only for debugging when things go wrong. Maybe someone else has a better idea to make things safer without hurting performance?

**Comment by awalter17** [comment]
That makes sense, thanks @axtimwalde and @ctrueden ! 

Additionally, I don't think there's a need for a `DebugCursor`. I think it is fine the way it is, as long as people are aware that `Cursor`s may not do any bounds checking and that their behavior outside of the bounds is undefined. Would it be useful to put something along those lines in the javadoc?

**Comment by ctrueden** [comment]
> Would it be useful to put something along those lines in the javadoc?

Sure. You could even tack it on to my PR #167, since it fits there.
