### ISSUE TITLE
History of API changes for ImgLib2

### ISSUE THREAD

**Issue by lvc** [imglib/imglib2#187]
Hi,

I'd like to share report on API changes and backward binary compatibility for the ImgLib2 library: https://abi-laboratory.pro/java/tracker/timeline/imglib2/

The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/net/imglib2/imglib2/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

The tool checks all public API methods and classes by default. Please let me know if it should not check some parts of the API (private, undocumented, etc.).

Thank you.

![imglib2-1](https://user-images.githubusercontent.com/1517837/31702953-d23a7990-b3e2-11e7-901c-c4252f32e75b.png)

![imglib2-2](https://user-images.githubusercontent.com/1517837/31702952-d21ec556-b3e2-11e7-94bf-730d1167730c.png)

**Comment by imagejan** [comment]
I added a link to that page on https://imagej.net/ImgLib2 so that it's more accessible.
