### ISSUE TITLE
imglib2-5.0.0 downstream packages update status

### ISSUE THREAD

**Issue by hanslovsky** [imglib/imglib2#204]
If you are adapting your packages to the changes introduced in imglib2-5.0.0 please log your progress here. That way we can avoid duplicate efforts and keep track of what has been done and what still needs to be done.

 - [x] [n5-label-multisets](https://github.com/saalfeldlab/n5-label-multisets/tree/imglib2-5)
 - [x] [n5-label-multisets-spark](https://github.com/saalfeldlab/n5-label-multisets-spark/tree/imglib2-v5)
 - [x] [n5-imglib2](https://github.com/saalfeldlab/n5-imglib2/pull/4)
 - [x] [bigdataviewer-core](https://github.com/bigdataviewer/bigdataviewer-core/pull/44)
 - [x] [bigdataviewer-vistools](https://github.com/bigdataviewer/bigdataviewer-vistools/pull/19)
 - [x] [bigcat/paintera](https://github.com/hanslovsky/bigcat/tree/multiscale-painting-imglib2-v5)
 - [x] [imglib2-algorithm](https://github.com/imglib/imglib2-algorithm/pull/64)
 - [x] [imagej-common](https://github.com/imagej/imagej-common/compare/imglib2-5)
 - [x] [scifio](https://github.com/scifio/scifio/compare/imglib2-v5)

**Comment by tpietzsch** [comment]
I'm on bigdataviewer-core and bigdataviewer-vistools. Already have it on branches etc, but working my way through imglib2 artifacts first. I can do these first, though, if needed.

**Comment by ctrueden** [comment]
I am working on imagej-common now.

**Comment by ctrueden** [comment]
I started working on scifio, but I don't understand `SCIFIOCellImgFactory` well enough to tackle it fully: https://github.com/scifio/scifio/compare/imglib2-v5. @tpietzsch If you have time to help me once you arrive in Moscow, I'd greatly appreciate it.

**Comment by ctrueden** [comment]
Released imglib2-script (0.2.3) and imglib2-ui (2.0.0).

**Comment by ctrueden** [comment]
Finished imglib2-tests. And imglib2-tutorials is nearly finished (see imglib2-v5 branch) except for `LifeForm`.

**Comment by hanslovsky** [comment]
As far as I can tell, all downstream dependencies have been updated. Thank you for your efforts!

If I missed any that were not updated, please re-open.

**Comment by ctrueden** [comment]
Some components still do not compile:

## imglib/imglib2-tutorials
```
[ERROR] /Users/curtis/code/imglib/imglib2-tutorials/src/main/java/game/LifeForm.java:[78,8] game.LifeForm is not abstract and does not override abstract method getNativeTypeFactory() in net.imglib2.type.NativeType
[ERROR] /Users/curtis/code/imglib/imglib2-tutorials/src/main/java/game/LifeForm.java:[113,9] method does not override or implement a method from a supertype
[ERROR] /Users/curtis/code/imglib/imglib2-tutorials/src/main/java/game/LifeForm.java:[117,90] cannot find symbol
  symbol:   method createIntInstance(long[],net.imglib2.util.Fraction)
  location: variable storageFactory of type net.imglib2.img.NativeImgFactory<game.LifeForm>
```

## fiji/SPIM_Registration
```
[ERROR] /Users/curtis/code/fiji/SPIM_Registration/src/main/java/spim/process/fusion/boundingbox/BigDataViewerBoundingBox.java:[162,159] incompatible types: net.imglib2.RealInterval cannot be converted to net.imglib2.Interval
[ERROR] /Users/curtis/code/fiji/SPIM_Registration/src/main/java/spim/process/fusion/boundingbox/BigDataViewerBoundingBox.java:[166,110] cannot find symbol
  symbol:   method min(int)
  location: interface net.imglib2.RealInterval
[ERROR] /Users/curtis/code/fiji/SPIM_Registration/src/main/java/spim/process/fusion/boundingbox/BigDataViewerBoundingBox.java:[167,110] cannot find symbol
  symbol:   method max(int)
  location: interface net.imglib2.RealInterval
```
/cc @StephanPreibisch 

## saalfeldlab/bigwarp
```
[ERROR] /Users/curtis/code/saalfeldlab/bigwarp/src/main/java/bigwarp/BigWarpRealExporter.java:[299,67] incompatible types: net.imglib2.img.Img<T> cannot be converted to net.imglib2.img.imageplus.ImagePlusImg<T,?>
[ERROR] /Users/curtis/code/saalfeldlab/bigwarp/src/main/java/bigwarp/BigWarpARGBExporter.java:[232,67] incompatible types: net.imglib2.img.Img<T> cannot be converted to net.imglib2.img.imageplus.ImagePlusImg<T,?>
```
/cc @bogovicj 

You can reproduce by updating the pom-scijava parent to `22.0.0-SNAPSHOT` and then building with:
```
mvn -Denforcer.skip=true clean package
```
Maintainers: please push fixes to a branch `imglib2-v5` or similar. Once we are certain everything plays nicely together I can cut pom-scijava 22.0.0 and merge the fixes with this newly cut parent version. But I'd rather not cut any more intermediate/transitionary pom-scijava versions if possible.

**Comment by hanslovsky** [comment]
Thanks for keeping track @ctrueden !

**Comment by etarena** [comment]
got it for Coloc 2 : https://github.com/fiji/Colocalisation_Analysis/commit/c6cc68efb11838ff46b3753dae021a2fce12dee7

**Comment by bogovicj** [comment]
Bigwarp:
https://github.com/saalfeldlab/bigwarp/commit/74c0a649ddc776de5a3f79b64db67db837406f68

**Comment by ctrueden** [comment]
Thanks @bogovicj. Mind if I push a tweaked version of that based on pom-scijava 21.0.0 (for a reproducible build) to master?

**Comment by ctrueden** [comment]
@bogovicj I assumed you were OK with it: saalfeldlab/bigwarp@fbe21747ef8b484540ef0858bf0f7dabc13fa2d7.

**Comment by ctrueden** [comment]
@StephanPreibisch Update SPIM_Registration: fiji/SPIM_Registration@e835fc3657d618b58a13dd24d368341f090a977e. And released 5.0.19. Changes were simple, but I did not test, so please do so if you have any concerns.

**Comment by ctrueden** [comment]
OK, I filed an issue for the only remaining known thing. imglib/imglib2-tutorials#5. Everything else is solved AFAIK, so closing again!

**Comment by tpietzsch** [comment]
> OK, I filed an issue for the only remaining known thing: imglib/imglib2-tutorials#5. Everything else is solved AFAIK, so closing again!

I will take care of this next week. Tutorials need to be ready for the learnathon...
