### ISSUE TITLE
Converters.convert method names and signatures can shadow each other

### ISSUE THREAD

**Issue by acardona** [imglib/imglib2#235]
In ```Converters```, there are methods named ```convert``` that take either an ```IterableInterval``` or a ```RandomAccessibleInterval```. Given that ```Img```, and many ImgLib2 data objects, implement both ```IterableInterval``` and ```RandomAccessibleInterval```, issues emerge--at least, from scripting languages like jython--when it comes to choosing one ```convert``` method over the other. While in many cases there isn't any issue, a clear issue arises when jython happens to prefer the ```Converters.convert``` methods that take an ```IterableInterval``` as argument and return an object whose class implements ```IterableInterval``` but not ```RandomAccessibleInterval```, because then the ```ImageJFunctions.wrap``` methods don't work: they require a ```RandomAccessibleInterval```.

The workaround, at least in jython, is to pick the desired ```convert``` method using reflection, which is cumbersome to say the least.

Ideally, a convenience class like ```Converters``` would not have identically named methods like ```convert(IterableInterval, SamplerConverter)``` and ```convert(RandomAccessibleInterval, SamplerConverter)```, given the issue explained above.

One easy solution is to add to ```Converters``` methods named like ```convertII``` and ```convertRAI```, or some such (perhaps ```convertIterableInterval``` and ```convertRandomAccessibleInterval```), that redirect to the currently existing methods.

**Comment by tpietzsch** [comment]
Yes, I ran into this also from java...

I even sneakily used
`RandomAccessibleInterval` instead of `Img` in imglib2-introductory-workshop:
https://github.com/imglib/imglib2-introductory-workshop/blob/00932397a2c1b36b402e52ea5653878209610e34/src/main/java/t04accessibles/T04E05Converters.java#L18
to avoid having to write (and explain) a cast here:
https://github.com/imglib/imglib2-introductory-workshop/blob/00932397a2c1b36b402e52ea5653878209610e34/src/main/java/t04accessibles/T04E05Converters.java#L32

> One easy solution is to add to `Converters` methods named like `convertII` and `convertRAI`, or some such (perhaps `convertIterableInterval` and `convertRandomAccessibleInterval`), that redirect to the currently existing methods.

Not nice, but would be a convenient workaround.

Another option (also not nice) would be to rename the `convert(IterableInterval, ...)` to `convertII`.
That would break more downstream code, but I think not too much. Converting RAIs should be the more commonly used variant.

Or we do a three-step thing. where we add `convertII` and `convertRAI` and deprecate `convert(IterableInterval, ...)`. Then later remove `convert(IterableInterval, ...)` (move implementation to convertII()) and deprecate `convertRAI`. Then later remove `convertRAI`.

@axtimwalde @StephanPreibisch @hanslovsky @bogovicj @maarzt any opinions?

**Comment by acardona** [comment]
Thanks @tpietzsch for looking into this. Whichever the solution, I am hoping for a quick one--the issue is not complicated.

**Comment by axtimwalde** [comment]
Java does the right thing when explicitly casting the input which for me is good enough, never using Img (aka RAI & Iterable) anyways.  Scripting interpreters somehow screw it up, despite explicit casts.  Actually, please try in Jython, I am speaking for Beanshell, still my favorite horror show.  There (because nothing matters anyways), I typically do this horrible trick
```java
Views.interval(Converters.convert(Views.extendZero(img), converter, type), img)
```
which works because RA is not Iterable and Views and Converters are not talking to each other...
I am pro adding the RAI method forever and marking it with a snarky comment that this is only for scripting.

**Comment by maarzt** [comment]
I see to options:
1. The problem occurs for objects the implement ```IterableInterval``` and ```RandomAccessibleInterval```. In 99.99% of the cases these objects implement ```Img```. So adding a third method Converters.convert(Img<T>, Converter<T,S>, S), will fix the problem.
2. Rename to ```Converters.convertII```.

**Comment by hanslovsky** [comment]
> I am pro adding the RAI method forever and marking it with a snarky comment that this is only for scripting.

I don't think that comment is necessary. I would rather not have to cast in Java as well.


> The problem occurs for objects the implement IterableInterval and RandomAccessibleInterval. In 99.99% of the cases these objects implement Img. So adding a third method Converters.convert(Img, Converter<T,S>, S), will fix the problem.

I do like that solution best. Unfortunately, this will not work for `IntervalView`, which you get from `Views.interval`, for example. To get around that, we could introduce another generic parameter like this (`ConvertedRandomAccessibleIterableInterval` does not exist yet):
```java
public static < A, B extends Type< B >, I extends RandomAccessible<A> & IterableInterval<A>> ConvertedRandomAccessibleIterableInterval< A, B, I > convert(
		final I source,
		final Converter< ? super A, ? super B > converter,
		final B b)
{
	return new ConvertedRandomAccessibleIterableInterval<>( source, converter, b );
}
```

This are the relevant use cases that I can think of:
```java
final RandomAccessibleInterval<IntType> rai = ArrayImgs.ints(1, 2);
final RandomAccessible<IntType> ra = ArrayImgs.ints(1, 2);
final IterableInterval<IntType> ii = ArrayImgs.ints(1, 2);
final Img<IntType> img = ArrayImgs.ints(1, 2);
final IntervalView<IntType> interval = Views.interval(ra, rai);

Converters.convert(rai, new TypeIdentity<>(), new IntType());         // works
Converters.convert(ra, new TypeIdentity<>(), new IntType());          // works
Converters.convert(ii, new TypeIdentity<>(), new IntType());          // works
Converters.convert(img, new TypeIdentity<>(), new IntType());         // does not work
Converters.convert(interval, new TypeIdentity<>(), new IntType());    // does not work
convert(img, new TypeIdentity<>(), new IntType());                    // would work
convert(interval, new TypeIdentity<>(), new IntType());               // would work
```
The last two lines would be the new method

**Comment by acardona** [comment]
Hi @maarzt : the ```Img``` approach may not work from e.g. jython (python), a language that doesn't know multiple method arity and therefore will pick the first ```convert``` that matches via reflection (I don't know in what order) which may be the wrong one. There would now be three: the two existing ones, and the ```Img``` one. I guess the chances that it would work would go up to 2/3 from the current 1/2. With ```Img``` being alphabetically earlier than ```IterableInterval```, there's a chance the ```Img``` may always work, but this is fragile.

Hi @axtimwalde : a ```convertRAI(RandomAccessibleInterval, ...)``` would be clear and simple, and would always work. I vote for this. The point of ```Converters``` is to ease the pain. In its absence, if I'd want a method that always works, I can invoke directly the method body of ```Converters.convert(RandomAccessibleInterval, Converter```, but that'd be beyond the point. Your hack to ```Views.extendZero``` is clever, but again, the point of ```Converters``` is to make it all easy.

Can I submit a pull request for a new method ```Converters.convertRAI```?

**Comment by tpietzsch** [comment]
If @hanslovsky suggestion works, I would prefer that over adding new method names.

**Comment by tpietzsch** [comment]
> Can I submit a pull request for a new method `Converters.convertRAI`?

I'm not so sure we should go out of our way to please scripting languages. Such workaround methods like `convertRAI` could live in a separate package (`imglib2-script`?). In this case, I think it's fine to add it, but I would not make it a rule.

**Comment by acardona** [comment]
In any case here's the pull request https://github.com/imglib/imglib2/pull/242

**Comment by acardona** [comment]
Well @tpietzsch in this case you've indicated that even from java you have to cast and work around the issue.

**Comment by hanslovsky** [comment]
Not in case of [this solution](https://github.com/imglib/imglib2/issues/235#issuecomment-459380131)

**Comment by tpietzsch** [comment]
I merged the PR.
I would still welcome addition of @hanslovsky solution to not have to call `convertRAI` from Java.

**Comment by tpietzsch** [comment]
Hmm. Unfortunately, as @maarzt pointed out, @hanslovsky solution will not work because of type erasure. Example to convince myself:
```java
interface IA {
	String getA();
}

interface IB {
	String getB();
}

static String f( IA input ) {
	return input.getA();
}

static < I extends IA & IB > String f( I input ) {
	return input.getA() + input.getB();
}
```
will not compile: `'f(IA)' clashes with 'f(I)'; both methods have same erasure.

**Comment by hanslovsky** [comment]
Also, this works (spot the difference!) :smile: :smile::
```
interface IA {
	String getA();
}

interface IB {
	String getB();
}

static String f( IA input ) {
	return input.getA();
}

static < I extends IB & IA > String f( I input ) {
	return input.getA() + input.getB();
}
```

**Comment by ctrueden** [comment]
@tpietzsch wrote:
> I'm not so sure we should go out of our way to please scripting languages.

Please remember that most people coding against ImageJ are using scripting languages rather than writing in Java. Java is too hard for most people to bother with.

**Comment by tpietzsch** [comment]
> Please remember that most people coding against ImageJ are using scripting languages rather than writing in Java. Java is too hard for most people to bother with.

Ok, maybe better:
I'm not so sure we should go out of our way to please scripting languages ***at this low level***.

**Comment by acardona** [comment]
Hi @tpietzsch, just to add that ```Converters```, ```Views``` and ```RealViews``` are what makes ImgLib2 accessible and, even, trivial to use from scripting languages. Ensuring that these classes are usable as intended is part of what we are discussing here. So far, this has been the only case where an issue arose, that I know of, and the issue exists even from java, as you reported yourself.

So thanks very much for merging the PR!
