### ISSUE TITLE
Should Cell implement Interval (or extend AbstractInterval)?

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2#239]
I found myself wanting to use a `Cell` in `Views.interval( ... )`
Given [this](https://github.com/imglib/imglib2/blob/fb42809c5fa400f1f3a11f43e3931acfb93148ae/src/main/java/net/imglib2/img/cell/Cell.java#L57-L59) I was surprised that it doesn't already. 

Though I presume `Cell`s are supposed to be "small", and I guess this is why their dimensions are stored as an `int[]`?  Because of that, it may not be a very easy change.

Alternatively, could we have a method somewhere that returns an `Interval` from a `Cell`?

**Comment by tpietzsch** [comment]
Good idea. If they implement `Interval` that doesn't add anything to the memory footprint. I wouldn't extend `AbstractInterval`.
A PR would be very welcome. but maybe we wait until #232 is merged...

**Comment by tpietzsch** [comment]
> A PR would be very welcome. but maybe we wait until #232 is merged...
it's merged now...

**Comment by hanslovsky** [comment]
This is probably fixed with #251 and can be closed, no?
