### ISSUE TITLE
ImgPlus with 3 channels is wrongly displayed as RGB

### ISSUE THREAD

**Issue by manerotoni** [imglib/imglib2#275]
Hello,

I find some inconsistencies when displaying ImgPlus. Three channels are displayed as a RGB image in imageJ, 4 channels are displayed correctly. How can we force the display not to use RGB?
Here is a code that shows the described behaviour

Antonio

```
import io.scif.img.ImgIOException;
import net.imagej.ImageJ;
import net.imagej.ImgPlus;
import net.imagej.axis.Axes;
import net.imagej.axis.AxisType;
import net.imglib2.img.array.ArrayImgs;
import net.imglib2.type.numeric.integer.UnsignedByteType;
import org.apache.commons.io.FilenameUtils;

public class wrongDisplayRGB {
    public static void main( final String[] args ) throws ImgIOException {
        ImgPlus<UnsignedByteType> ch3 = new ImgPlus(ArrayImgs.unsignedBytes(100, 100, 100, 3),
                "3 channels -> RGB?",
                new AxisType[] {Axes.X, Axes.Y, Axes.Z, Axes.CHANNEL});
        ImgPlus<UnsignedByteType> ch4 = new ImgPlus(ArrayImgs.unsignedBytes(100, 100, 100, 4),
                "4 channels",
                new AxisType[] {Axes.X, Axes.Y, Axes.Z, Axes.CHANNEL});
        ImageJ ij;
        ij = new ImageJ();
        ij.ui().showUI();
        ij.ui().show(ch3); // is shown as RGB
        ij.ui().show(ch4); // is shown as 4 color image
    }
}
```

**Comment by hanslovsky** [comment]
Hi @manerotoni, imglib2 ImgLib2 is not concerned with displaying images. The [https://github.com/imagej/imagej](ImageJ repository) or the [Image.sc Forum](https://image.sc) would probably be the appropriate places for this question.

**Comment by bogovicj** [comment]
I think there is already a [forum post](https://forum.image.sc/t/imgplus-with-3-channels-is-wrongly-displayed-as-rgb-imglib2/32074), but agree with @hanslovsky , that this seems more of an issue with imagej2 / scijava than imglib2

**Comment by ctrueden** [comment]
Thanks @manerotoni, I responded on the forum! I don't think there's a "bug" here per se, just a confusing detail of the imagej-legacy integration. But if you encounter further suspicious behavior, feel free to file further issues relating to the `net.imagej` packages at https://github.com/imagej/imagej/issues.
