### ISSUE TITLE
static field containing an ExecutorService in Parallelization class

### ISSUE THREAD

**Issue by acardona** [imglib/imglib2#283]
The ```Parallelization``` class has a ```ThreadLocal``` ```executors``` static field, initialized with an ```ExecutorService```. This will keep eg. 64 threads (for a 64-core CPU) idle for any Thread that loads this class. This is not optimal. What's the rational behind this?

**Comment by tpietzsch** [comment]
That's not true. The field is initialized with `TaskExecutors.multiThreaded()` which will not create any threads but forward to Java's common `ForkJoinPool`.
