### ISSUE TITLE
No ImageJFunctions

### ISSUE THREAD

**Issue by amchev** [imglib/imglib2#284]
Many of the imglib2 examples use the ImageJFunctions library but that does not exist in the imglib2 project. 

There is no "net.imglib2.img.diplay.imagej.ImageJFunctions"

**Comment by bogovicj** [comment]
`net.imglib2.img.diplay.imagej.ImageJFunctions` lives in this repo:
https://github.com/imglib/imglib2-ij

Are these the examples you're referring to?
https://imagej.net/ImgLib2_Examples

**Comment by ctrueden** [comment]
@amchev The examples make use of [quite a few different dependencies](https://github.com/imglib/imglib2-tutorials/blob/ea30fb4c1bf587888c8832f3e27ad8312565fba2/pom.xml#L134-L178) besides only `net.imglib2:imglib2`. Are you using Maven to work with the examples repository?

**Comment by amchev** [comment]
@bogovicj yes those are the examples I am referring to.

@ctrueden yes I am using maven.
