### ISSUE TITLE
Add methods/constructors taking (Real)Localizables where relevant

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2#285]
What do we think about adding methods/constructors taking `Localizables` or `RealLocalizables` where they currently take only `long[]` or `double[]` inputs?

E.g.
```
RealPoint minPt
RealPoint maxPt;
new FinalRealInterval( minPt, maxPt );
```

This could get annoying if we also wanted to support all of:
```
double[] min;
double[] max;
new FinalRealInterval( minPt, max );
new FinalRealInterval( min, maxPt );
```
but may not actually be so bad.

Related: a `Localizables.asDoubleArray( RealLocalizable )` method similar to [`asLongArray`](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/util/Localizables.java#L51) would help if we don't want to go this route.

This came up [on gitter](https://gitter.im/imglib/imglib2?at=5e7cbc5104405b1a718e6a80), in the context of a `net.imglib2.realtransform.Translation3D`
@imagejan 
@hanslovsky 
@igorpisarev

**Comment by tpietzsch** [comment]
> What do we think about adding methods/constructors taking `Localizables` or `RealLocalizables` where they currently take only `long[]` or `double[]` inputs?

Would be nice, yes.

> new FinalRealInterval( minPt, max );

I wouldn't add those proactively...


I'm definitely for `Localizables.asDoubleArray()`.
It might be also a good idea to put these as static methods into the respective interfaces, i.e.,
`static long[] asLongArray( Localizable )` could go into `Localizable` and
`static double[] asDoubleArray( RealLocalizable )` could go into `RealLocalizable`.
(I would however not add non-static default methods `default long[] asLongArray()` to Localizable etc, because that might be pretty confusing in derived classes, e.g., `RandomAccess.asLongArray()`.)

**Comment by hanslovsky** [comment]
> I wouldn't add those proactively...

I agree with that

> (I would however not add non-static default methods `default long[] asLongArray()` to `Localizable` etc, because that might be pretty confusing in derived classes, e.g., `RandomAccess.asLongArray()`.)

That makes total sense. What if those default methods would be named differently? e.g.
```
double[] RealLocalizable.localizeAsDoubleArray();
long[] Localizable.localizeAsLongArray();
```
and their 32bit counter-parts.

**Comment by tpietzsch** [comment]
> What if those default methods would be named differently?

I still don't have a 100% good feeling with that. Maybe.

**Comment by ctrueden** [comment]
I don't have a strong opinion about whether we add those default methods. But if so, I would suggest:

```java
int[] localizeInt()
long[] localizeLong()
double[] localizeDouble()
```

This is in line with the already existing `localize(int[])`, `localize(long[])` etc., and naming-wise consistent with elsewhere e.g. `getRealFloat()`, `getRealDouble()`.

And of course it's more concise.

**Comment by axtimwalde** [comment]
I am with @hanslovsky and @ctrueden, default methods with descriptive names shouldn't cause any trouble and be very convenient.
