### ISSUE TITLE
get type from typed interfaces

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2#311]
Consider adding
```
default T type() {...}
```
or similar for typed interfaces. See the gitter conversation [here](https://gitter.im/imglib/imglib2?at=62113936d1b64840db2ccadc).

@hanslovsky @tpietzsch @tischi

**Comment by bogovicj** [comment]
see https://github.com/imglib/imglib2/pull/312

**Comment by tpietzsch** [comment]
#312 is merged now.
