### ISSUE TITLE
ColorTables and ImageMetadata

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2#32]
Hi,

we are currently working on ColorTables for Labelings and therefore reviewed some of the existing code of the ColorTables.

We found something where we are not sure whether this is correct or not: ImgPlus<T> implements ImageMetadata which somehow maintains a ColorTable. ImgPlus can be of any type T (not restricted, especially not to RealType), but the ColorTable Interface assumes, that we always map a double value to a color (see e.g. 	public int lookupARGB(double min, double max, double value)).

We therefore thought about somehow generalizing the current ColorTable interface.

public interface ColorTable<X>{
public int getColorValue(X x); // you get back the color
public int getComponentCount(); // how many "channels" do we have (e.g. RGB, RGBA);
}

This implies that we have to type ImageMetadata<X>. Anyway, this assures, that ImgPlus<X> and ImageMetadata<X> have the same type and therefore a valid mapping of X -> Color is guaranteed. Additionally, we could reuse this interface for arbitrary type ColorTables (e.g. LabelingType -> Color, which is not a "ColorRange" implementation anymore, but a HashMap Implementation).

Any comment before we start refactoring?

Cheers,

Christian

**Comment by dietzc** [comment]
can be closed, as imglib2.meta moved to imagej-common world.

**Comment by ctrueden** [comment]
Yep! However, we should still think about how to make the color table support more integrated with ImgLib2 interfaces, etc.
