### ISSUE TITLE
[QUESTION] Error making axis transpositions

### ISSUE THREAD

**Issue by carlosuc3m** [imglib/imglib2#372]
Hello, 

I’m working with ImageJFunctions to wrap ImagePlus instances into RandomAccessibleIntervals, but I’m encountering some unexpected behavior that I’d appreciate some help with.

Here’s the code snippet I’m using:
```
	public static void main(String[] args) {
		ImagePlus imp = IJ.createImage("", 600, 400, 1, 32);
		RandomAccessibleInterval<FloatType> rai = ImageJFunctions.wrapFloat(imp);
		for (int i = 0; i < 2; i ++)
			rai = Views.addDimension(rai, 0, 0);
		int[] transformation = new int[] {2, 3,  1, 0};
		rai = rearangeAxes(rai, transformation);
		Cursor<FloatType> cursor = Views.flatIterable(rai).cursor();
		while (cursor.hasNext()) {
			cursor.get().get();
			cursor.fwd();
		}
		System.out.println(false);
	}
	
	public static <T extends NumericType<T> & RealType<T>> 
	RandomAccessibleInterval<T> rearangeAxes(RandomAccessibleInterval<T> rai, int[] orderChange){
		if (rai.dimensionsAsLongArray().length != orderChange.length)
			throw new IllegalArgumentException("The parameter 'orderChange' should have the same dimensions as the array provided witht he first parameter 'rai'.");
		List<Integer> checker = new ArrayList<Integer>();
		for (int i : orderChange) {
			if (!checker.contains(i))
				checker.add(i);
		}
		if (checker.size() != orderChange.length)
			throw new IllegalArgumentException("The 'orderChange' parameter should not contain repeated"
					+ " numbers and should go from 0 to rai.dimensionsAsLongArray().length - 1");
		long[] max = rai.maxAsPoint().positionAsLongArray();
		long[] min = rai.minAsPoint().positionAsLongArray();
		long[] tensorShape = rai.dimensionsAsLongArray();
		MixedTransform t = new MixedTransform( tensorShape.length, tensorShape.length );
		t.setComponentMapping(orderChange);
		long[] minMax = new long[tensorShape.length * 2];
		for (int i = 0; i < tensorShape.length; i ++) {
			minMax[i] = min[orderChange[i]];
			minMax[i + tensorShape.length] = max[orderChange[i]];
		}
		return Views.interval(new MixedTransformView<T>( rai, t ), 
				Intervals.createMinMax(minMax));
	}
	
```

I’m trying to wrap a 2D ImagePlus (width × height), add two empty dimensions, rearrange the axes to achieve batch × channels × height × width, and then perform a flat iteration over the resulting RandomAccessibleInterval.

However, I encounter a strange behavior:

  *  If the width of the image is larger than the height (e.g., 600 × 400), I get an ArrayIndexOutOfBoundsException.
  *  If the height is larger than or equal to the width, the code works fine.

I have reproduced the issue with an ArrayImg as well, so it doesn’t seem to be related to the ImagePlus wrapping:

`RandomAccessibleInterval<FloatType> rai = ArrayImgs.floats(new long[] {600, 400});`

It feels like the problem lies in how I’m performing the axis rearrangement, but I find it strange that it only happens when one dimension is larger than the other.

Has anyone experienced something similar or have suggestions on what might be causing this?

Thanks in advance for any insights!

Regards,
Carlos

**Comment by tpietzsch** [comment]
The inverse of the `orderChange` must be used for the `MixedTransformView`.
Its `transformToSource` argument means the transformation from View coordinates to Source (Image) coordinates.
That makes the "source space" of the transform the View coordinates and the "target space" is the Source (Image) coordinates. So its a bit of source/target terminology overload there...

This works:
```java
    public static <T extends NumericType<T> & RealType<T>>
    RandomAccessibleInterval<T> rearangeAxes(RandomAccessibleInterval<T> rai, int[] orderChange) {
        final int n = rai.numDimensions();
        final long[] min = new long[n];
        final long[] max = new long[n];
        final int[] invOrderChange = new int[n];
        for (int i = 0; i < n; i++) {
            min[i] = rai.min(orderChange[i]);
            max[i] = rai.max(orderChange[i]);
            invOrderChange[orderChange[i]] = i;
        }
        MixedTransform t = new MixedTransform(n, n);
        t.setComponentMapping(invOrderChange);
        return Views.interval(new MixedTransformView<>(rai, t), min, max);
    }
```
