### ISSUE TITLE
Port NIO-backed images to ImgLib2

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2#5]
In ImgLib1, there is support for NIO-backed primitive arrays in the mpicbg.imglib.container.basictypecontainer.array package, specifically the NIO\* classes. This was never translated to ImgLib2. It would be nice to do so, since NIO-backed arrays have [a few advantages](http://onjava.com/pub/a/onjava/2002/10/02/javanio.html), including allocation outside the heap, arrays larger than 2GB, and shared memory with native applications.

**Comment by hanslovsky** [comment]
Yes, let's do it!

**Comment by ctrueden** [comment]
We have a more concrete potential use case now: this would be a nice longer-term way forward for the [imglyb](https://github.com/imglib/imglyb) project so that we can maybe move away from [imglib2-unsafe](https://github.com/imglib/imglib2-unsafe).

**Comment by hanslovsky** [comment]
We might still need imglib2-unsafe, at least if we plan to support accesses with more than 2^31 entries. [`ByteBuffer.put`](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#put(int,%20byte)) can only process an `int` index and I am not aware of any other method that would write into a buffer with a `long` index.

**Comment by mkitti** [comment]
I've developed an interest in this, and I am considering picking up where @hanslovsky left off in #278. In particular, I would like to use this along with [com.sun.jna.Pointer.getByteBuffer](https://java-native-access.github.io/jna/4.2.1/com/sun/jna/Pointer.html#getByteBuffer-long-long-)

**Comment by haesleinhuepf** [comment]
Hey @mkitti, great initiative! I'm happy to help if necessary. See also discussion [here](https://github.com/SimpleITK/SimpleITK/issues/1215) ;-)

**Comment by mkitti** [comment]
@haesleinhuepf , thanks. The cross-reference is useful.

**Comment by mkitti** [comment]
@ctrueden , @haesleinhuepf I have a new PR candidate in #299. Will #299 address your needs?

One aspect not addressed is dealing with large memory blocks. The proposals I have seen to address that involve tiling the memory range with `ByteBuffers` or using some sort of factory to address `ByteBuffer` sized chunks at a time.

For example, JNA allows you to acquire a `ByteBuffer` at a `long` offset:
https://java-native-access.github.io/jna/4.2.1/com/sun/jna/Pointer.html#getByteBuffer-long-long-
That is supported by a JNI call `NewDirectByteBuffer`
https://github.com/java-native-access/jna/blob/e245cc96c6f45f313b89dde0e57fc34603965164/native/dispatch.c#L2541
https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer

To handle large memory blocks with imglib2, we could create a `CellImg` with each `Cell` backed by a `ByteBuffer`. It may be necessary to overlap the cells depending on the primitive type.
