### ISSUE TITLE
Consider allowing autoboxing

### ISSUE THREAD

**Issue by hinerm** [imglib/imglib2#53]
In places like [IntervalIndexer](https://github.com/imglib/imglib/blob/master/core/src/main/java/net/imglib2/util/IntervalIndexer.java) which use primitive arrays, it would be nice to consolidate their use with classes like PrimitiveArray or ArrayDataAccess. However, for the PrimitiveArray class there will be an autoboxing cost.

So we should run performance benchmarks to see what kind of hit it would take if autoboxing was allowed, as it wold significantly simplify the code for something like https://github.com/imglib/imglib/pull/51.

**Comment by tpietzsch** [comment]
Closing this because it seems outdated. Please reopen if this is still of interest to anyone...
