### ISSUE TITLE
Fix licensing incompatibilities with edu-mines-jtk

### ISSUE THREAD

**Issue by ctrueden** [imglib/imglib2#61]
The Mines Java Toolkit is [licensed under the CPL](http://inside.mines.edu/~dhale/jtk/license.html). This license is incompatible with the GPL—that is, you cannot release GPL software with dependencies on a CPL component. [From the GPL web site](http://www.gnu.org/licenses/license-list.html#CommonPublicLicense10):

> [The CPL] is a free software license. Unfortunately, its weak copyleft and choice of law clause make it incompatible with the GNU GPL.

In ImgLib2, the `imglib2-algorithms` package is licensed as BSD-2, and depends on Mines JTK. The `imglib2-algorithms-gpl` component is licensed as GPL and depends on `imglib2-algorithms`. In particular, `FFTConvolution` depends on `FFTMethods` which uses the Mines Java Toolkit. This situation is not legal.

The most ideal solution to this problem would be to eliminate all dependencies on Mines JTK, to avoid this conundrum in the future. But barring that, we could isolate all Mines-dependent code into its own subcomponent of `imglib2-algorithms`, perhaps `imglib2-algorithms-fft`.

@StephanPreibisch, what is your preference?

**Comment by ctrueden** [comment]
It is looking likely that Mines JTK will soon switch to the Apache v2 license (see dhale/jtk#12). Stay tuned.

**Comment by ctrueden** [comment]
The switch of JTK to APLv2 is complete. Once a new version of Mines JTK is released, we can update our components to use that release, and this problem will be resolved. I am going to close this particular issue now, since the `imglib2` core component does not actually depend on JTK anymore, and hence does not suffer from this particular licensing issue.

**Comment by bnorthan** [comment]
That's awesome.  Thanks @ctrueden, @dhale, and other Mines contributors.
