### ISSUE TITLE
Document IterableInterval range

### ISSUE THREAD

**Issue by hinerm** [imglib/imglib2#70]
It's not clear what the intended limitations of [IterableInterval](https://github.com/imglib/imglib/blob/master/core/src/main/java/net/imglib2/IterableInterval.java) are.. e.g., can there be gaps in the range of values covered by the interval?

It would be nice if the intended use here was documented.

**Comment by ctrueden** [comment]
I think with the merge of #168, this issue is resolved. The javadoc of `IterableInterval` now makes a statement that the iteration may _not necessarily_ include all coordinates within the containing `Interval`. It will depend on the type of `IterableInterval` in question.
