### ISSUE TITLE
SubIntervalIterable Cursors + Benchmark

### ISSUE THREAD

**Issue by Squareys** [imglib/imglib2#71]
Hello all!

@dietzc and me tried to clean-up the branch "subinterval-cursor" whose changes now appear in "si-cursor-clean", hopefully without changes unrelated to the subinterval cursors.

SubInterval Cursors are optimized cursors for certain intervals, e.g. given an N-D ArrayImg one can create an optimized cursor for subintervals over an arbitrary XY plane. We started working on this on the Konstanz Hackathon 2012 with @tpietzsch.

I also did benchmarking, which gave some surprising results. You may view them here:

http://pastebin.com/KDzq4Hfy

The most amazing fact is that the optimized cursors of PlanarImg and ArrayImg are about 100 times faster than the RandomAccessibleIntervalCursor!

Sadly especially the PlanarImg optimized cursor gets screwed over by JIT pretty bad when used after iterating over an ArrayImg first. As to be seen in the benchmark above, the optimized cursor is then suddenly slower than the RandomAccessibleIntervalCursor.

Also, the "optimized" LocalizingCursors are always slower than the "non optimized" ones. We haven't really found out why yet.

@tpietzsch:
I suggest you have a look at the code and benchmark and decide over which parts you want to merge, maybe find the reason for the slowness of the LocalizingCursors.

 Greetings, 
Jonathan

**Comment by dietzc** [comment]
this is already merged to master since a while.
