### ISSUE TITLE
Img/View based on Imgs

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2#9]
In some cases it would be nice to have an n-dimensional Img/View which wraps a set of m < n dimensional Imgs.

Example NtreeImg:
The higher the dimensionality of your NtreeImg, the slower it gets as in an iteration step it needs to check in any dimension. If I know that I access the Img/View plane-wise and my Img is let's say three dimensional,  I could convert it to an Img/View based on several two-dimensional NtreeImgs which can be iterated faster. The idea is actually analogous to a PlanarImg.

**Comment by tpietzsch** [comment]
@dietzc I think this has been addressed with `Views.stack()`? Can we close this issue?

**Comment by dietzc** [comment]
absolutely. thanks :+1:
