### ISSUE TITLE
net.imglib2.img.display.imagej.ImageJFunctions

### ISSUE THREAD

**Issue by 223daniel** [imglib/imglib2#93]
In the Fiji site Getting Started, there is code that includes the package net.imglib2.img.display.imagej.ImageJFunctions. However, I have downloaded the zip file and cannot find the package in my src/main/java. Is there any way to fix this?
Thank you

**Comment by hinerm** [comment]
Hi @223daniel 

>In the Fiji site Getting Started, there is code that includes the package 

Can you point to the code you're refering? I don't see any sample code on the [Getting Started](http://imagej.net/Getting_started) page.

>However, I have downloaded the zip file and cannot find the package in my src/main/java.

ImgLib2 classes are encapsulated in dedicated components, based on their functionality. For ImageJ-related functionality, you want [imglib2-ij](https://github.com/imglib/imglib2-ij)

**Comment by ctrueden** [comment]
@hinerm He probably means the [ImgLib2 - Getting Started](http://imagej.net/ImgLib2_-_Getting_Started) page.

**Comment by ctrueden** [comment]
Also, as I [mentioned on Gitter yesterday](https://gitter.im/imagej/imagej/archives/2015/06/29):
> As for the "documentation" pages, those are unfortunately not tied to CI so they fall out of date. My personal preference would be to migrate the "documentation" including "getting started" into the ImgLib2 Tutorials section, and tie it in to https://github.com/imglib/imglib2-tutorials with the rest.

**Comment by hinerm** [comment]
:+1:

**Comment by 223daniel** [comment]
Thank you so much!

**Comment by dietzc** [comment]
seems to be resolved
