### ISSUE TITLE
"Inefficient": RandomAccessibleIntervalCursor

### ISSUE THREAD

**Issue by dietzc** [imglib/imglib2#99]
Hi all,

I'm wondering if we could be a bit more efficient here:

https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/view/RandomAccessibleIntervalCursor.java#L104

We don't really need `l`.

*  `l * index` is always negative if index is negative
*  `l * dimensions[ 0 ] = index`, right?

Or am I missing something?

Cheers and a nice weekend,

Christian

**Comment by axtimwalde** [comment]
<code>l * dimension[0] ?= index</code> because they are integers, the block is a rounding/ modulo operation that is different fornegative and positive numbers.

**Comment by dietzc** [comment]
Ah Ok. Thanks for clarification.
